---
title: "Catchment Comparison"
author: "Daniel Thurber"
date: "1/18/2022"
output: pdf_document
---
initialize the session
```{r}
mypath <- 'C:/Users/Daniel/Documents/Research/data/dataframes/'  #leave this as directory
library(naniar)
library(snotelr)
library(stringr)
library(zoo, warn.conflicts = F)
library(raster, warn.conflicts = F)



sitecodes <- c('LR_FB_BA', 'LR_TG_BA', 'BC_CONF_A', 'TF_CONF_A','RHF_CONF_A', 'RS_CONF_A', 
               'TF_SAWM_A', 'SPC_CONF_A', 'LR_WC_A', 'LR_GCB_A', 'WCS_CONF_A', 'LR_FD')
sitenames <- c('Franklin Basin', 'Tony Grove', 'Beaver Creek', 'Temple Fork', 'Right Hand Fork','Ricks Spring', 
               'TF at Sawmill', 'Spawn Creek', 'Above Wood Camp', 'Guinavah Campground','Wood Camp Spring','First Dam')
siteabbr <- c('FB', 'TG', 'BC', 'TF','RH', 'RS', 
              'TS', 'SC', 'WC', 'GC', 'WS','FD')

sitesnotel <- c(1115, 1115, 1114,1013,1013, 823, 
              1013, 1098, 1113, 1113, 823,1098)
ST.el <- c(7250, 7250, 7705,7406,7406, 8474, 
           7406, 8270, 6332, 6332, 8474,8270)*0.3048

#FB_484, GCS_1114, KN_1115, TF_1013, TGL_823, TGRS_1113, UDD_1098
#GCS: 7705, KN: 7250, TF: 7406, USUDD: 8270, TGRS: 6332, TGL: 8474, FB: 8140

startyear <- c(2015,2015,2016,2016,2017,2016,
               2019,2019,2019,2019,2019,2015)
acf.sites <- c('FB_', 'TG_', 'BC_', 'TF_', 'RH_', 'RS_', 'TS_', 'SC_', 'WC_', 'GC_', 'WS_', 'FD_')
acf.years <- c('15','16','17','18','19','20','21')
plot.points <- c(1,5,7,8,15,17,19)

linecols <- c('brown3', 'goldenrod', 'forestgreen', 'bisque4', 'slateblue', 'tan1', 
              'aquamarine3', 'magenta4', 'sienna3','cyan','violetred2','yellow2')
linetypes <- c(1,1,1,1,1,3,1,1,1,1,4,1)
rgbmat <- col2rgb(linecols)
wydates <- data.frame(wyday = seq(1,366),
day=format(seq.Date(as.Date('2019-10-1','%Y-%m-%d'),as.Date('2020-09-30','%Y-%m-%d'),1),'%m-%d'))
comp.df <- read.csv(paste0('C:/Users/Daniel/Documents/Research/data/dataframes/catchment_comparison.csv'))
corr.df <- read.csv('C:/Users/Daniel/Documents/Research/data/dataframes/correlograms.csv')
colnames(comp.df)[4:171] <- str_sub(colnames(comp.df)[4:171],-6,-1) #make sure column names are only the last 6 characters
row.names(comp.df) <- sitecodes
data.frame(A=row.names(comp.df),B=comp.df[,'site_name'])==data.frame(A=sitecodes, B = sitenames)#verify that row names match up

head(comp.df[,which(colSums(comp.df[,4:171],na.rm = T)!=0)+3],3)
```

Take a look at the color palette, adjust if desired
```{r, fig.height=1.5, fig.width=7}
linecols <- c('brown3', 'goldenrod', 'forestgreen', 'bisque4', 'slateblue', 'tan1', 
              'aquamarine3', 'magenta4', 'sienna3','cyan','violetred2','yellow2')
par(mar = c(4,0,0,0))
image(1:length(linecols),.1, as.matrix(1:length(linecols)), col = linecols, yaxt = 'n', ylab = '', xlab = 'catchment', xaxt = 'n')
axis(side = 1, at = 1:length(linecols), labels = siteabbr)
```

Initialize catchment areas in km^2
```{r}
site.areas <- c(65.9767, #FB
                277.965, #TG
                103.4015, #BC
                41.4076, #TF
                65.1986, #RH
                NA, #RS
                8.6085, #TS
                14.7168, #SC
                403.874, #WC
                520.8331, #GC
                NA, #WS
                554 #FD
                )
comp.vars <- data.frame('VAR' = c('KST', 'HYI', 'MDS','VAA','MHS', 'MDE'),
                        'ax.lab' = c('karst area', 'hypsometric integral','median slope', 'average aspect', 'median hillshade', 'median elevation'),
                        'main.lab' = c('karst', 'hypsometry', 'slope', 'aspect', 'hillshade', 'elevation'))
```

### Describe responses by catchment variables
```{r}
sites <- 1:12 #select all sites
#sites <- which(!is.na(site.areas)) #select surface catchments
#sites <- c(1:5) #select custom sites
years <- c(1:7) #numbers 1-7 for '15-'21
funct <- 'MCA'
y.title <- 'Lag to end of correlation'
y.units <- '(days)'
catch.var <- 6
x.var <- paste0('CV_',comp.vars[catch.var,1])
x.title <- comp.vars[catch.var,2]
plot.title <- paste('Melt C ACF correlation by',comp.vars[catch.var,3])

sel.sites <-   sitecodes[sites]

sel.cols <- paste0(acf.years[years],'_',funct)

new.comp <- comp.df[sel.sites,c(x.var,sel.cols)]
new.comp
check <- 1
normed <- ''
```

normalize by area (cms to mm/hr) if appropriate
```{r}
runblock <- seq(1:check)
for (y in sel.cols)
new.comp[,y] <- new.comp[,y]/site.areas[sites]*3.6
check <- NA
y.units <- 'mm/hr'
normed <- 'Normalized'
```

```{r}

ylab <- paste(y.title,y.units)
pt.types <- plot.points[years]
par(mar = c(4,4,4,6))
plot(new.comp[,sel.cols[1]]~new.comp[,x.var], ylim = range(new.comp[,sel.cols], na.rm = T) ,
     main = paste(normed,plot.title),xlab = x.title, ylab = ylab, type = 'n')
for (x in 1:length(sel.cols)){
  points(new.comp[,sel.cols[x]]~new.comp[,x.var], col = linecols[sites], pch = pt.types[x])

}
legend('right', inset = -0.2, legend = c(siteabbr[sites],paste0('20',acf.years[years])), pch = c(rep(19, times = length(sites)),pt.types), col = c(linecols[sites], rep('black', times = length(years))), xpd = T)
```

### Describe responses by annual metrics
Create dataframes of the independent and dependent variables to look at
```{r}
sites <- 1:12 #select all sites
#sites <- which(!is.na(site.areas)) #select surface catchments
sites <- c(1:5) #select custom sites
years <- c(1:4) #numbers 1-7 for '15-'21
funct <- 'QAV'
y.title <- 'Average annual discharge'
y.units <- '(m3/s)'
x.var <- 'TMP'
x.title <- 'Total Fall Rain'
plot.title <- paste('Average Discharge by','Fall Precip')

sel.sites <-   sitecodes[sites]

y.cols <- paste0(acf.years[years],'_',funct)
x.cols <- paste0(acf.years[years],'_',x.var)
y.df <- comp.df[sel.sites,y.cols]
x.df <- comp.df[sel.sites,x.cols]

x.df
y.df
sum(is.na(x.df)-is.na(y.df))==0 #checks that both dataframes have NAs in the same places

```

Add code chunk to normalize by area
```{r}

```


Generate plot
```{r}
ii <- 1
site <- sitecodes[ii]
site.in <- as.numeric(x.df[site,])
site.out <- as.numeric(y.df[site,])
pt.types <- plot.points[years]


par(mar = c(4,4,4,6))

plot(site.out~site.in, type = 'n', xlab = x.title, ylab = y.title, main = plot.title, 
     ylim = range(y.df, na.rm = T), xlim = range(x.df, na.rm =T ))

for (ii in sites) {
site <- sitecodes[ii]
site.in <- as.numeric(x.df[site,])
site.out <- as.numeric(y.df[site,])  
  
points(site.out~site.in, col = linecols[ii], pch = plot.points[1:4])
}


legend('right', inset = -0.2, legend = c(siteabbr[sites],paste0('20',acf.years[years])), pch = c(rep(19, times = length(sites)),pt.types), col = c(linecols[sites], rep('black', times = length(years))), xpd = T)
```

