---
title: "Correlation Comparison"
author: "Daniel Thurber"
date: "11/22/2021"
output: pdf_document
---
initialize the session
```{r}
mypath <- 'C:/Users/Daniel/Documents/Research/data/dataframes/'  #leave this as directory
library(naniar)
library(snotelr)
library(stringr)
library(zoo, warn.conflicts = F)
library(raster, warn.conflicts = F)



sitecodes <- c('LR_FB_BA', 'LR_TG_BA', 'BC_CONF_A', 'TF_CONF_A','RHF_CONF_A', 'RS_CONF_A', 
               'TF_SAWM_A', 'SPC_CONF_A', 'LR_WC_A', 'LR_GCB_A', 'WCS_CONF_A', 'LR_FD')
sitenames <- c('Franklin Basin', 'Tony Grove', 'Beaver Creek', 'Temple Fork', 'Right Hand Fork','Ricks Spring', 
               'TF at Sawmill', 'Spawn Creek', 'Above Wood Camp', 'Guinavah Campground','Wood Camp Spring','First Dam')
siteabbr <- c('FB', 'TG', 'BC', 'TF','RH', 'RS', 
              'TS', 'SC', 'WC', 'GC', 'WS','FD')

sitesnotel <- c(1115, 1115, 1114,1013,1013, 823, 
              1013, 1098, 1113, 1113, 823,1098)
ST.el <- c(7250, 7250, 7705,7406,7406, 8474, 
           7406, 8270, 6332, 6332, 8474,8270)*0.3048

#FB_484, GCS_1114, KN_1115, TF_1013, TGL_823, TGRS_1113, UDD_1098
#GCS: 7705, KN: 7250, TF: 7406, USUDD: 8270, TGRS: 6332, TGL: 8474, FB: 8140
startyear <- c(2015,2015,2016,2016,2017,2016,
               2019,2019,2019,2019,2019,2015)
acf.sites <- c('FB_', 'TG_', 'BC_', 'TF_', 'RH_', 'RS_', 'TS_', 'SC_', 'WC_', 'GC_', 'WS_', 'FD_')
acf.years <- c('15','16','17','18','19','20','21')

linecols <- c('brown3', 'goldenrod', 'forestgreen', 'bisque4', 'slateblue', 'tan1', 
              'aquamarine3', 'magenta4', 'sienna3','cyan','violetred2','yellow2')
linetypes <- c(1,1,1,1,1,3,1,1,1,1,4,1)
rgbmat <- col2rgb(linecols)
wydates <- data.frame(wyday = seq(1,366),
day=format(seq.Date(as.Date('2019-10-1','%Y-%m-%d'),as.Date('2020-09-30','%Y-%m-%d'),1),'%m-%d'))
comp.df <- read.csv(paste0('C:/Users/Daniel/Documents/Research/data/dataframes/catchment_comparison.csv'))
corr.df <- read.csv('C:/Users/Daniel/Documents/Research/data/dataframes/correlograms.csv')
colnames(comp.df)[4:171] <- str_sub(colnames(comp.df)[4:171],-6,-1) #make sure column names are only the last 6 characters
row.names(comp.df) <- sitecodes
data.frame(A=row.names(comp.df),B=comp.df[,'site_name'])==data.frame(A=sitecodes, B = sitenames)#verify that row names match up

head(comp.df[,which(colSums(comp.df[,4:171],na.rm = T)!=0)+3],3)
```

### Compare correlation functions between sites in a given year



```{r}
#enter the 
sites <- siteabbr[1:5] #enter the 2-letter codes for the sites you want to compare
years <- c('18')
season <- c('F','M')
variable <- c('Q')
funct <- c('C')

sel.codes <- colnames(corr.df)

#filter by site
sel.cols <- which(str_sub(sel.codes,1,2) %in% sites) 
sel.codes <- sel.codes[sel.cols]

#filter by year
sel.cols <- which(str_sub(sel.codes,4,5) %in% years) 
sel.codes <- sel.codes[sel.cols]

#filter by season
sel.cols <- which(str_sub(sel.codes,7,7) %in% season) 
sel.codes <- sel.codes[sel.cols]

#filter by variable
sel.cols <- which(str_sub(sel.codes,9,9) %in% variable) 
sel.codes <- sel.codes[sel.cols]

#filter by function
sel.cols <- which(str_sub(sel.codes,11,11) %in% funct) 
sel.codes <- sel.codes[sel.cols]

sel.codes
```


```{r}
c.comp.df <- corr.df[c('lag',sel.codes)]
head(c.comp.df)
```

Generate plot label string
```{r}
lab <- paste0("Q|SWIT CCF for 20",years[1])
lab
(colnames(c.comp.df)[-1])
```

```{r}
#set line parameters
lncolors <- c(1,2,3,4,5, 1,2,3,4,5) #number based on site
linetypes <- c(1,1,1,1,1,2,2,2,2,2) #1 for runoff, 2 for melt
ln.names <- c('FB', 
              'TG',
              'BC',
              'TF',
              'RH',
              'FB - melt', 
              'TG - melt',
              'BC - melt',
              'TF - melt',
              'RH - melt')

#Create a blank plot
plot(c.comp.df$lag, c.comp.df$acf, col=linecols[1],
     ylab = 'Correlation', xlab = 'Lag (days)', ylim = c(0.1,1), xlim = c(0,50), 
     main = lab,
     type = 'n', #change to 'n' to hide, 'l' to show
     )
#Draw all lines on the plot
for(i in c(2:ncol(c.comp.df))){
  lines(c.comp.df[i], col = linecols[lncolors[i-1]],lty=linetypes[i-1])
}

abline(h = 0.2, lty = 3)

legend('topright', legend = ln.names, lty = linetypes, col = linecols[lncolors]) 
```




```{r}
comp.names <- sitenames[sites]
#identify sites to compare
comp.sites <- acf.sites[sites] 
#FB_, TG_, BC_, TF_, RH_, RS_, TS_, SC_, WC_, GC_, SS_, SD_

#If years are absent, manage that by commenting out operations later
acf.year <- '18' #choose year for comparison 
acf.season <- '_F' #_F, _W, _B - set season code (runoff, wet, baseflow)
acf.variable <- '_C' #_Q, _C - set discharge/conductance variable
acf.function <- "_A" #_A, _C, _S - set ACF, CCF(UEB), or CCF(SNOTEL) function
acf.codes <- paste0(comp.sites, acf.year, acf.season, acf.variable, acf.function)
acf.codes
plot.type <- 'C Autocorrelation'
```
```{r}
plot(corr.df$lag, corr.df[,acf.codes[1]],
     ylab = 'Correlation', xlab = 'Lag (days)', ylim = c(-0.2,0.99), xlim = c(0,50), 
     main = paste0(plot.type, ' for water year 20', acf.year), #write title each time!
     type = 'n', #change to 'n' to hide, 'l' to show
     )

for (i in 1:length(sites)) {
  
#for SC cross correlations, add a negative sign before the vector call
lines(corr.df[acf.codes[i]], col = linecols[sites[i]],xlim = c(0,50))
}

abline(h = 0.2, lty = 3)
abline(h = -0.2, lty = 3)

legend('bottomleft', legend = sitenames[sites], lty = 1, col = linecols[sites])
```




### Compare correlation metrics (lag times)
```{r}
corr.df <- read.csv('C:/Users/Daniel/Documents/Research/data/dataframes/corr_metrics.csv')
corr.df$season[which(corr.df$season == F)]='F'

colnames(corr.df)[1]='site'
#colnames(corr.df)[5]='funct'
```


```{r}
#enter the 
sites <- c('FB','TG','BC', 'TF', 'RH', 'TS', 'SC', 'WC', 'GC') #enter the codes for the sites you want to compare
years <- c(19)
season <- c('F') #F - full runoff  #B - Baseflow
variable <- c('Q') #Q, C
funct <- c('A') #A - ACF, CP - SWIT ccf lag to peak, CL - SWIT ccf lag to 0.2
comp.factor <- 'site'
c.comp.df <- (corr.df)

#filter by site
sel.rows <- which(c.comp.df$site %in% sites) 
c.comp.df <- c.comp.df[sel.rows,]

#filter by year
sel.rows <- which(c.comp.df$year %in% years) 
c.comp.df <- c.comp.df[sel.rows,]
#filter by season
sel.rows <- which(c.comp.df$season %in% season) 
c.comp.df <- c.comp.df[sel.rows,]
#filter by variable
sel.rows <- which(c.comp.df$variable %in% variable) 
c.comp.df <- c.comp.df[sel.rows,]

#filter by function
sel.rows <- which(c.comp.df$funct %in% funct) 
c.comp.df <- c.comp.df[sel.rows,]

c.comp.df[,comp.factor] <-  as.factor(c.comp.df[,comp.factor])
#c.comp.df$year <- as.factor(c.comp.df$year)
#c.comp.df$site <- as.factor(c.comp.df$site)

c.comp.df
```

```{r}
title <- 'Q ACF total lag times - 2019'
y.label <- 'lag time (days)'
x.label <- 'catchment area'
```


```{r}
par(mar=c(4,4,5,6))
plot(c.comp.df$value~c.comp.df$area, col=c.comp.df[,comp.factor], pch = 19,
     main = title, ylab = y.label, xlab = x.label)
#axis(3, at = unique(c.comp.df$karst_frac), labels = unique(c.comp.df$site), srt = -90)
legend('right',title = comp.factor,legend = unique(c.comp.df[,comp.factor]), col = c.comp.df[,comp.factor], pch = 19, inset = c(-.13,0), xpd = T)
```


Generate plot label string
```{r}
lab <- "Discharge ACF for 2020"
lab
colnames(c.comp.df)
```

```{r}
#set line parameters
lncolors <- c(1,2,3,1,2,3) #number based on site
linetypes <- c(1,1,1,2,2,2) #1 for runoff, 2 for baseflow
ln.names <- c('FB', 'TF','RH', 'FB - base', 'TF - base','RH - base')

plot(c.comp.df$lag, c.comp.df$acf, col=linecols[1],
     ylab = 'Correlation', xlab = 'Lag (days)', ylim = c(0.1,1), xlim = c(0,50), 
     main = lab,
     type = 'n', #change to 'n' to hide, 'l' to show
     )

for(i in c(2:ncol(c.comp.df))){
  lines(c.comp.df[i], col = linecols[lncolors[i-1]],lty=linetypes[i-1])
}

abline(h = 0.2, lty = 3)

legend('topright', legend = ln.names, lty = linetypes, col = linecols[lncolors]) 
```




```{r}
comp.names <- sitenames[sites]
#identify sites to compare
comp.sites <- acf.sites[sites] 
#FB_, TG_, BC_, TF_, RH_, RS_, TS_, SC_, WC_, GC_, SS_, SD_

#If years are absent, manage that by commenting out operations later
acf.year <- '18' #choose year for comparison 
acf.season <- '_F' #_F, _W, _B - set season code (runoff, wet, baseflow)
acf.variable <- '_C' #_Q, _C - set discharge/conductance variable
acf.function <- "_A" #_A, _C, _S - set ACF, CCF(UEB), or CCF(SNOTEL) function
acf.codes <- paste0(comp.sites, acf.year, acf.season, acf.variable, acf.function)
acf.codes
plot.type <- 'C Autocorrelation'
```
```{r}
plot(corr.df$lag, corr.df[,acf.codes[1]],
     ylab = 'Correlation', xlab = 'Lag (days)', ylim = c(-0.2,0.99), xlim = c(0,50), 
     main = paste0(plot.type, ' for water year 20', acf.year), #write title each time!
     type = 'n', #change to 'n' to hide, 'l' to show
     )

for (i in 1:length(sites)) {
  
#for SC cross correlations, add a negative sign before the vector call
lines(corr.df[acf.codes[i]], col = linecols[sites[i]],xlim = c(0,50))
}

abline(h = 0.2, lty = 3)
abline(h = -0.2, lty = 3)

legend('bottomleft', legend = sitenames[sites], lty = 1, col = linecols[sites])
```