---
title: "LRO data availability"
author: "Daniel Thurber"
date: "11/8/2021"
output: pdf_document
---
initialize the session
```{r}
mypath <- 'C:/Users/Daniel/Documents/Research/data/dataframes/'  #leave this as directory
library(naniar)
library(snotelr)
library(stringr)
library(plotrix)

sitecodes <- c('LR_FB_BA', 'LR_TG_BA', 'BC_CONF_A', 'TF_CONF_A','RHF_CONF_A', 'RS_CONF_A', 
               'TF_SAWM_A', 'SPC_CONF_A', 'LR_WC_A', 'LR_GCB_A', 'WCS_CONF_A', 'LR_FD')
sitenames <- c('Franklin Basin', 'Tony Grove', 'Beaver Creek', 'Temple Fork', 'Right Hand Fork','Ricks Spring', 
               'TF at Sawmill', 'Spawn Creek', 'Above Wood Camp', 'Guinavah Campground','Wood Camp Spring','First Dam')
siteabbr <- c('FB', 'TG', 'BC', 'TF','RH', 'RS', 
              'TS', 'SC', 'WC', 'GC', 'WS','FD')

sitesnotel <- c(1115, 1115, 1114,1013,1013, 823, 
              1013, 1098, 1113, 1113, 823,1098)
#FB_484, GCS_1114, KN_1115, TF_1013, TGL_823, TGRS_1113, UDD_1098

acf.sites <- c('FB_', 'TG_', 'BC_', 'TF_', 'RH_', 'RS_', 'TS_', 'SC_', 'WC_', 'GC_', 'WS_', 'FD_')
acf.years <- c('15','16','17','18','19','20','21')

linecols <- c('brown3', 'goldenrod', 'forestgreen', 'bisque4', 'slateblue', 'tan1', 
              'aquamarine3', 'magenta4', 'sienna3','cyan','violetred2','yellow2')
linetypes <- c(1,1,1,1,1,3,1,1,1,1,4,1)
rgbmat <- col2rgb(linecols)
wydates <- data.frame(wyday = seq(1,366),
day=format(seq.Date(as.Date('2019-10-1','%Y-%m-%d'),as.Date('2020-09-30','%Y-%m-%d'),1),'%m-%d'))
```

```{r}
alldata <- read.csv(file = 'C:/Users/Daniel/Documents/Research/data/dataframes/patched_data/all_data.csv', stringsAsFactors = F)
alldata$date <- as.Date(alldata$date,'%Y-%m-%d')
```

Pull in data from each site and add it to the "alldata" dataframe and save to .csv
---
```{r}

i <- 12
site <- sitecodes[i]               #enter site code for file upload and export
sitename <- sitenames[i]        #enter site name for plotting
siteabv <- siteabbr[i]
paste('Site:', sitecodes[i], '-', sitenames[i])
   #the line color vector is used by other plotting scripts as well.  Attempt to keep it consistent

```


```{r}
patchdf <- read.csv(paste0('C:/Users/Daniel/Documents/Research/data/dataframes/patched_data/',site,'_patched.csv'))
patchdf$date <- as.Date(patchdf$date,'%Y-%m-%d')
choice.vars <- c('date','discharge','conductance','temp','cpatch','qpatch')
patchdf <- patchdf[,which(colnames(patchdf)%in% choice.vars)]
paste('Site:', sitecodes[i], '-', sitenames[i])
```




```{r}
alldata <- merge.data.frame(alldata, patchdf, by = 'date', all = T)
paste('Site:', sitecodes[i], '-', sitenames[i], 'added')

```

```{r}
colnames(alldata)[which(colnames(alldata) == 'discharge')] <- paste0(siteabv,'_Q')
colnames(alldata)[which(colnames(alldata) == 'conductance')] <- paste0(siteabv,'_SC')
colnames(alldata)[which(colnames(alldata) == 'temp')] <- paste0(siteabv,'_T')
colnames(alldata)[which(colnames(alldata) == 'cpatch')] <- paste0(siteabv,'_CP')
colnames(alldata)[which(colnames(alldata) == 'qpatch')] <- paste0(siteabv,'_QP')
paste('Site:', sitenames[i], "data renamed")

```

```{r}
write.csv(alldata, file = 'C:/Users/Daniel/Documents/Research/data/dataframes/patched_data/all_data.csv')
```
---

Plot availability of data for each site
Sets the spacing for the horizontal lines
```{r}
p <- rep(seq(0,.8, by=.1), each=1) 
q <- rep(c(.045), times = 9)
g <- c(p+q,.93,.96)
g
```

Plot w/o temp
```{r, fig.height=8, fig.width=9}
daterange <- range(alldata$date)
par(mar=c(4,8,2,6))
plot((seq(1:nrow(alldata))/nrow(alldata))~alldata$date, type = 'n', yaxt = 'n',ylab ='', xlab = 'Date (tick marks: Jan. 1, white lines: Mar. 15)', ylim = c(0,1), main = "Data availability of LRO aquatic sites")
#axis(side = 2, at = seq(.1,1, by = 0.1), labels = F, tick = F)
axis(side = 2, at = c(seq(.05,0.85, by = 0.1),.915,.945,.975), labels = siteabbr,tick = F, las = 1)
rect(xleft = daterange[1],ybottom = 0,xright = daterange[2],ytop = .99, col = "darkolivegreen3", border = NA)
abline(h = c(1:9)/10-.005, col = 'black', lwd = 6)
axis(side = 4, at = c(.025,.065,.425,.465,.825,.865,.915,.945,.975), labels = c("Q","SC","Q","SC","Q","SC","Q","Q","Q"), las = 1, tick = F)
#abline(v=as.Date("2018-1-1","%Y-%m-%d"))
par(xpd=T)
legend(x = 'topright', inset = c(-.19,.25),pch = 15, col = c('darkolivegreen3','steelblue','firebrick2'),legend = c('observed','Patched','missing'))
b=0.0001

#data for LR_FB_BA
ablineclip(v = alldata$date[which(is.na(alldata$FB_Q))], col = 'steelblue', y1=b, y2=b+0.045)
ablineclip(v = alldata$date[which(is.na(alldata$FB_QP))], col = 'firebrick2', y1=b, y2=b+0.045)

ablineclip(v = alldata$date[which(is.na(alldata$FB_C))], col = 'steelblue', y1=b+0.046, y2=b+0.09)
ablineclip(v = alldata$date[which(is.na(alldata$FB_CP))], col = 'firebrick2', y1=b+0.046, y2=b+0.09)

b = b+0.1

##data for LR_TG_BA
ablineclip(v = alldata$date[which(is.na(alldata$TB_Q))], col = 'steelblue', y1=b, y2=b+0.045)
ablineclip(v = alldata$date[which(is.na(alldata$TB_QP))], col = 'firebrick2', y1=b, y2=b+0.045)

ablineclip(v = alldata$date[which(is.na(alldata$TB_SC))], col = 'steelblue', y1=b+0.046, y2=b+0.09)
ablineclip(v = alldata$date[which(is.na(alldata$TB_CP))], col = 'firebrick2', y1=b+0.046, y2=b+0.09)

b = b+0.1

##data for BC_CONF_A
ablineclip(v = alldata$date[which(is.na(alldata$BC_Q))], col = 'steelblue', y1=b, y2=b+0.045)
ablineclip(v = alldata$date[which(is.na(alldata$BC_QP))], col = 'firebrick2', y1=b, y2=b+0.045)

ablineclip(v = alldata$date[which(is.na(alldata$BC_SC))], col = 'steelblue', y1=b+0.046, y2=b+0.09)
ablineclip(v = alldata$date[which(is.na(alldata$BC_CP))], col = 'firebrick2', y1=b+0.046, y2=b+0.09)

b = b+0.1

##data for TF_CONF_A
ablineclip(v = alldata$date[which(is.na(alldata$TF_Q))], col = 'steelblue', y1=b, y2=b+0.045)
ablineclip(v = alldata$date[which(is.na(alldata$TF_QP))], col = 'firebrick2', y1=b, y2=b+0.045)

ablineclip(v = alldata$date[which(is.na(alldata$TF_SC))], col = 'steelblue', y1=b+0.046, y2=b+0.09)
ablineclip(v = alldata$date[which(is.na(alldata$TF_CP))], col = 'firebrick2', y1=b+0.046, y2=b+0.09)

b = b+0.1

##data for RHF_CONF_A
ablineclip(v = alldata$date[which(is.na(alldata$RH_Q))], col = 'steelblue', y1=b, y2=b+0.045)
ablineclip(v = alldata$date[which(is.na(alldata$RH_QP))], col = 'firebrick2', y1=b, y2=b+0.045)

ablineclip(v = alldata$date[which(is.na(alldata$RH_SC))], col = 'steelblue', y1=b+0.046, y2=b+0.09)
ablineclip(v = alldata$date[which(is.na(alldata$RH_CP))], col = 'firebrick2', y1=b+0.046, y2=b+0.09)

b = b+0.1

##data for RS_CONF_A
ablineclip(v = alldata$date[which(is.na(alldata$RS_Q))], col = 'steelblue', y1=b, y2=b+0.045)
ablineclip(v = alldata$date[which(is.na(alldata$RS_QP))], col = 'firebrick2', y1=b, y2=b+0.045)

ablineclip(v = alldata$date[which(is.na(alldata$RS_SC))], col = 'steelblue', y1=b+0.046, y2=b+0.09)
ablineclip(v = alldata$date[which(is.na(alldata$RS_CP))], col = 'firebrick2', y1=b+0.046, y2=b+0.09)

b = b+0.1

##data for TF_SAWM_A
ablineclip(v = alldata$date[which(is.na(alldata$TS_Q))], col = 'steelblue', y1=b, y2=b+0.045)
ablineclip(v = alldata$date[which(is.na(alldata$TS_QP))], col = 'firebrick2', y1=b, y2=b+0.045)

ablineclip(v = alldata$date[which(is.na(alldata$TS_SC))], col = 'steelblue', y1=b+0.046, y2=b+0.09)
ablineclip(v = alldata$date[which(is.na(alldata$TS_CP))], col = 'firebrick2', y1=b+0.046, y2=b+0.09)

b = b+0.1

##data for SPC_CONF_A
ablineclip(v = alldata$date[which(is.na(alldata$SC_Q))], col = 'steelblue', y1=b, y2=b+0.045)
ablineclip(v = alldata$date[which(is.na(alldata$SC_QP))], col = 'firebrick2', y1=b, y2=b+0.045)

ablineclip(v = alldata$date[which(is.na(alldata$SC_SC))], col = 'steelblue', y1=b+0.046, y2=b+0.09)
ablineclip(v = alldata$date[which(is.na(alldata$SC_CP))], col = 'firebrick2', y1=b+0.046, y2=b+0.09)

b = b+0.1

##data for LR_WC_A
ablineclip(v = alldata$date[which(is.na(alldata$WC_Q))], col = 'steelblue', y1=b, y2=b+0.045)
ablineclip(v = alldata$date[which(is.na(alldata$WC_QP))], col = 'firebrick2', y1=b, y2=b+0.045)

ablineclip(v = alldata$date[which(is.na(alldata$WC_SC))], col = 'steelblue', y1=b+0.046, y2=b+0.09)
ablineclip(v = alldata$date[which(is.na(alldata$WC_CP))], col = 'firebrick2', y1=b+0.046, y2=b+0.09)

b = b+0.1

##data for LR_GCB_A
ablineclip(v = alldata$date[which(is.na(alldata$GC_Q))], col = 'steelblue', y1=b, y2=b+0.03)
ablineclip(v = alldata$date[which(is.na(alldata$GC_QP))], col = 'firebrick2', y1=b, y2=b+0.03)

ablineclip(v = alldata$date[which(is.na(alldata$WS_Q))], col = 'steelblue', y1=b+0.03, y2=b+0.06)
ablineclip(v = alldata$date[which(is.na(alldata$WS_QP))], col = 'firebrick2', y1=b+0.03, y2=b+0.06)

b = b+0.1

#add annotations and reference lines
text(x = as.Date('2019-09-01','%Y-%m-%d'), y = 1.07, labels = 'End of UEB outputs')

abline(v = as.Date('2018-10-01','%Y-%m-%d'))

abline(v = alldata$date[which(format(alldata$date,'%m-%d')=='03-15')], col= 'white')
abline(h = g, col= "gray42")

```

Plot w/ temp data
```{r, fig.height=8, fig.width=9}
daterange <- range(alldata$date)
par(mar=c(4,8,2,6))
plot((alldata$X/nrow(alldata))~alldata$date, type = 'n', yaxt = 'n',ylab ='', xlab = 'Date (tick marks: Jan. 1, white lines: Mar. 15)', ylim = c(0,1), main = "Data availability of LRO aquatic sites")
#axis(side = 2, at = seq(.1,1, by = 0.1), labels = F, tick = F)
axis(side = 2, at = seq(.05,0.95, by = 0.1), labels = sitecodes,tick = F, las = 1)
rect(xleft = daterange[1],ybottom = 0,xright = daterange[2],ytop = .99, col = "darkolivegreen3", border = NA)
abline(h = c(1:9)/10-.005, col = 'black', lwd = 6)
axis(side = 4, at = c(.415,.445,.475), labels = c("Q","SC","T"), las = 1, tick = F)
#abline(v=as.Date("2018-1-1","%Y-%m-%d"))
par(xpd=T)
legend(x = 'topright', inset = c(-.19,.1),pch = 15, col = c('darkolivegreen3','steelblue','firebrick2'),legend = c('observed','Patched','missing'))
b=0

#data for LR_FB_BA
ablineclip(v = alldata$date[which(is.na(alldata$FB_Q))], col = 'steelblue', y1=b, y2=b+0.03)
ablineclip(v = alldata$date[which(is.na(alldata$FB_QP))], col = 'firebrick2', y1=b, y2=b+0.03)

ablineclip(v = alldata$date[which(is.na(alldata$FB_SC))], col = 'steelblue', y1=b+0.03, y2=b+0.06)
ablineclip(v = alldata$date[which(is.na(alldata$FB_CP))], col = 'firebrick2', y1=b+0.03, y2=b+0.06)

ablineclip(v = alldata$date[which(is.na(alldata$FB_T))], col = 'firebrick2', y1=b+0.06, y2=b+0.09)
b = b+0.1


##data for LR_TG_BA
ablineclip(v = alldata$date[which(is.na(alldata$TB_Q))], col = 'steelblue', y1=b, y2=b+0.03)
ablineclip(v = alldata$date[which(is.na(alldata$TB_QP))], col = 'firebrick2', y1=b, y2=b+0.03)

ablineclip(v = alldata$date[which(is.na(alldata$TB_SC))], col = 'steelblue', y1=b+0.03, y2=b+0.06)
ablineclip(v = alldata$date[which(is.na(alldata$TB_CP))], col = 'firebrick2', y1=b+0.03, y2=b+0.06)

ablineclip(v = alldata$date[which(is.na(alldata$TB_T))], col = 'firebrick2', y1=b+0.06, y2=b+0.09)
b = b+0.1

##data for BC_CONF_A
ablineclip(v = alldata$date[which(is.na(alldata$BC_Q))], col = 'steelblue', y1=b, y2=b+0.03)
ablineclip(v = alldata$date[which(is.na(alldata$BC_QP))], col = 'firebrick2', y1=b, y2=b+0.03)

ablineclip(v = alldata$date[which(is.na(alldata$BC_SC))], col = 'steelblue', y1=b+0.03, y2=b+0.06)
ablineclip(v = alldata$date[which(is.na(alldata$BC_CP))], col = 'firebrick2', y1=b+0.03, y2=b+0.06)

ablineclip(v = alldata$date[which(is.na(alldata$BC_T))], col = 'firebrick2', y1=b+0.06, y2=b+0.09)
b = b+0.1

##data for TF_CONF_A
ablineclip(v = alldata$date[which(is.na(alldata$TF_Q))], col = 'steelblue', y1=b, y2=b+0.03)
ablineclip(v = alldata$date[which(is.na(alldata$TF_QP))], col = 'firebrick2', y1=b, y2=b+0.03)

ablineclip(v = alldata$date[which(is.na(alldata$TF_SC))], col = 'steelblue', y1=b+0.03, y2=b+0.06)
ablineclip(v = alldata$date[which(is.na(alldata$TF_CP))], col = 'firebrick2', y1=b+0.03, y2=b+0.06)

ablineclip(v = alldata$date[which(is.na(alldata$TF_T))], col = 'firebrick2', y1=b+0.06, y2=b+0.09)
b = b+0.1

##data for RHF_CONF_A
ablineclip(v = alldata$date[which(is.na(alldata$RH_Q))], col = 'steelblue', y1=b, y2=b+0.03)
ablineclip(v = alldata$date[which(is.na(alldata$RH_QP))], col = 'firebrick2', y1=b, y2=b+0.03)

ablineclip(v = alldata$date[which(is.na(alldata$RH_SC))], col = 'steelblue', y1=b+0.03, y2=b+0.06)
ablineclip(v = alldata$date[which(is.na(alldata$RH_CP))], col = 'firebrick2', y1=b+0.03, y2=b+0.06)

ablineclip(v = alldata$date[which(is.na(alldata$RH_T))], col = 'firebrick2', y1=b+0.06, y2=b+0.09)
b = b+0.1

##data for RS_CONF_A
ablineclip(v = alldata$date[which(is.na(alldata$RS_Q))], col = 'steelblue', y1=b, y2=b+0.03)
ablineclip(v = alldata$date[which(is.na(alldata$RS_QP))], col = 'firebrick2', y1=b, y2=b+0.03)

ablineclip(v = alldata$date[which(is.na(alldata$RS_SC))], col = 'steelblue', y1=b+0.03, y2=b+0.06)
ablineclip(v = alldata$date[which(is.na(alldata$RS_CP))], col = 'firebrick2', y1=b+0.03, y2=b+0.06)

ablineclip(v = alldata$date[which(is.na(alldata$RS_T))], col = 'firebrick2', y1=b+0.06, y2=b+0.09)
b = b+0.1

##data for TF_SAWM_A
ablineclip(v = alldata$date[which(is.na(alldata$TS_Q))], col = 'steelblue', y1=b, y2=b+0.03)
ablineclip(v = alldata$date[which(is.na(alldata$TS_QP))], col = 'firebrick2', y1=b, y2=b+0.03)

ablineclip(v = alldata$date[which(is.na(alldata$TS_SC))], col = 'steelblue', y1=b+0.03, y2=b+0.06)
ablineclip(v = alldata$date[which(is.na(alldata$TS_CP))], col = 'firebrick2', y1=b+0.03, y2=b+0.06)

ablineclip(v = alldata$date[which(is.na(alldata$TS_T))], col = 'firebrick2', y1=b+0.06, y2=b+0.09)
b = b+0.1

##data for SPC_CONF_A
ablineclip(v = alldata$date[which(is.na(alldata$SC_Q))], col = 'steelblue', y1=b, y2=b+0.03)
ablineclip(v = alldata$date[which(is.na(alldata$SC_QP))], col = 'firebrick2', y1=b, y2=b+0.03)

ablineclip(v = alldata$date[which(is.na(alldata$SC_SC))], col = 'steelblue', y1=b+0.03, y2=b+0.06)
ablineclip(v = alldata$date[which(is.na(alldata$SC_CP))], col = 'firebrick2', y1=b+0.03, y2=b+0.06)

ablineclip(v = alldata$date[which(is.na(alldata$SC_T))], col = 'firebrick2', y1=b+0.06, y2=b+0.09)
b = b+0.1

##data for LR_WC_A
ablineclip(v = alldata$date[which(is.na(alldata$WC_Q))], col = 'steelblue', y1=b, y2=b+0.03)
ablineclip(v = alldata$date[which(is.na(alldata$WC_QP))], col = 'firebrick2', y1=b, y2=b+0.03)

ablineclip(v = alldata$date[which(is.na(alldata$WC_SC))], col = 'steelblue', y1=b+0.03, y2=b+0.06)
ablineclip(v = alldata$date[which(is.na(alldata$WC_CP))], col = 'firebrick2', y1=b+0.03, y2=b+0.06)

ablineclip(v = alldata$date[which(is.na(alldata$WC_T))], col = 'firebrick2', y1=b+0.06, y2=b+0.09)
b = b+0.1

##data for LR_GCB_A
ablineclip(v = alldata$date[which(is.na(alldata$GC_Q))], col = 'steelblue', y1=b, y2=b+0.03)
ablineclip(v = alldata$date[which(is.na(alldata$GC_QP))], col = 'firebrick2', y1=b, y2=b+0.03)

ablineclip(v = alldata$date[which(is.na(alldata$WS_Q))], col = 'steelblue', y1=b+0.03, y2=b+0.06)
ablineclip(v = alldata$date[which(is.na(alldata$WS_QP))], col = 'firebrick2', y1=b+0.03, y2=b+0.06)

ablineclip(v = alldata$date[which(is.na(alldata$LR_GCB_A_T))], col = 'firebrick2', y1=b+0.06, y2=b+0.09)
b = b+0.1

#add annotations and reference lines
text(x = as.Date('2019-09-01','%Y-%m-%d'), y = 1.02, labels = 'End of UEB outputs')

abline(v = as.Date('2018-10-01','%Y-%m-%d'))

abline(v = alldata$date[which(format(alldata$date,'%m-%d')=='03-15')], col= 'white')
abline(h = g, col= "gray42")
```


