---
title: "O2_processing"
author: "Daniel Thurber"
date: "8/31/2021"
output: pdf_document
---
```{r}
linecols <- c('brown3', 'goldenrod', 'forestgreen', 'bisque4', 'slateblue', 'sienna3', 'aquamarine3', 'magenta4')
rgbmat <- col2rgb(linecols)/255
```


```{r}
basin.name <- 'Cub River'
sitename <- 'Franklin Basin'
```

```{r}
snoflow <- read.csv(paste0('C:/Users/Daniel/Documents/Research/data/O2_time_series/',basin.name,'_',sitename,'.csv'))
snoflow$date <- as.Date(snoflow$date,'%Y-%m-%d')
```

```{r}
range(snoflow$WY)
```
```{r}
WY <- 1981
wydf <- snoflow[which(snoflow$WY == WY),]
wydf$swi <- wydf$melt+wydf$rain

```



```{r}
study.int <- c(120,360)
a <- study.int[1]  #index of starting time
b <- study.int[2]   #index of ending time based on study interval

win1 <- c(a,a+110)  #red rect
win2 <- c(a+0,a+195)  #yellow rect
win3 <- c(a+0,a+210)  #green rect
win4 <- c(a+0,a+220)   #gray rect
win5 <- c(a,a+230)    #blue rect

yrange <- c(0,max(wydf$discharge[study.int[1]:study.int[2]], na.rm = T))

barplot(wydf$swi[a:b], axes = F)
axis(side = 4, at = pretty(range(wydf$swi[study.int[1]:study.int[2]]), n = 2))
par(new=T)
plot(wydf$discharge, xlim = study.int, ylim = yrange, type = 'l', ylab = 'discharge', 
     main = paste('discharge at', basin.name,'for', WY)
     )

#highlight ranges for each window of CCF analysis
rect(xleft=win1[1], xright=win1[2], ybottom = 0, ytop=.2*yrange[2], border = NA,  
     col = rgb(rgbmat[1,1],rgbmat[2,1],rgbmat[3,1], alpha = 0.5))
rect(xleft=win2[1], xright=win2[2], ybottom = .2*yrange[2], ytop=.4*yrange[2], border = NA,  
     col = rgb(rgbmat[1,2],rgbmat[2,2],rgbmat[3,2], alpha = 0.5))
rect(xleft=win3[1], xright=win3[2], ybottom = .4*yrange[2], ytop=.6*yrange[2], border = NA,  
     col = rgb(rgbmat[1,3],rgbmat[2,3],rgbmat[3,3], alpha = 0.5))
rect(xleft=win4[1], xright=win4[2], ybottom = .6*yrange[2], ytop=.8*yrange[2], border = NA,  
     col = rgb(rgbmat[1,4],rgbmat[2,4],rgbmat[3,4], alpha = 0.5))
rect(xleft=win5[1], xright=win5[2], ybottom = .8*yrange[2], ytop=1*yrange[2],  border = NA, 
     col = rgb(rgbmat[1,5],rgbmat[2,5],rgbmat[3,5], alpha = 0.5))

abline(v = which(is.na(wydf$discharge)), col = 'red')
abline(v = which(wydf$day=='02-15'), col = 'green')
```
```{r}
#automatically enters date ranges to the legend for each window
win.names <- c(paste(wydf$day[win1[1]], 'to', wydf$day[win1[2]]),
               paste(wydf$day[win2[1]], 'to', wydf$day[win2[2]]), 
               paste(wydf$day[win3[1]], 'to', wydf$day[win3[2]]),
               paste(wydf$day[win4[1]], 'to', wydf$day[win4[2]]),
               paste(wydf$day[win5[1]], 'to', wydf$day[win5[2]]))


#win.names <- c('3/5-8/12','4/4-10/11','4/4-8/12','3/5-10/11','4/4-11/10')
```


Compute CCF of Q | swi within each window.
```{r}
lagmax <- 200
acf1 <- ccf(wydf$discharge[win1[1]:win1[2]], wydf$swi[win1[1]:win1[2]], lag.max = lagmax, 
             plot = F, na.action = na.pass)
acf2 <- ccf(wydf$discharge[win2[1]:win2[2]], wydf$swi[win2[1]:win2[2]], lag.max = lagmax, 
             plot = F, na.action = na.pass)
acf3 <- ccf(wydf$discharge[win3[1]:win3[2]], wydf$swi[win3[1]:win3[2]], lag.max = lagmax, 
             plot = F, na.action = na.pass)
acf4 <- ccf(wydf$discharge[win4[1]:win4[2]], wydf$swi[win4[1]:win4[2]], lag.max = lagmax, 
             plot = F, na.action = na.pass)
acf5 <- ccf(wydf$discharge[win5[1]:win5[2]], wydf$swi[win5[1]:win5[2]], lag.max = lagmax, 
             plot = F, na.action = na.pass)

```

```{r}
plot(acf1$lag, acf1$acf, type = 'l', col=linecols[1],
     ylab = 'Correlation', xlab = 'Lag (days)', ylim = c(-0.2,0.9), xlim = c(0,50), 
     main = paste('Q|swi Crosscorrelation window sensitivity:', sitename, wydf$WY[a]))
lines(acf2$acf[(lagmax+2):(lagmax*2+1)], col = linecols[2],xlim = c(0,lagmax))
lines(acf3$acf[(lagmax+2):(lagmax*2+1)], col = linecols[3],xlim = c(0,lagmax))
lines(acf4$acf[(lagmax+2):(lagmax*2+1)], col = linecols[4])
lines(acf5$acf[(lagmax+2):(lagmax*2+1)], col = linecols[5])

abline(h = 0.2, lty = 3)
abline(h = -0.2, lty = 3)

legend('bottomleft', legend = win.names, lty = 1, col = linecols[1:5]) 
```







